version: '3.8'

services:
  parser_service:
    build: .
    container_name: parser_service
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
